## Преобразование данных КРУТа в удобный формат

In [1]:
import pandas as pd

In [4]:
data, tags = pd.read_csv('data2.csv'), pd.read_csv('tags.csv')
data.head()

,Unnamed: 0,annotated,annotator_sentence.id,id,tagged,text
0,0,1,1,1,"<span class=""token"" data-toggle=""tooltip"" titl...",задание 5: В ответах на вопросы использовались...
1,1,1,2,1,"«<span class=""token"" data-toggle=""tooltip"" ti...",«Профессора и студент »
2,2,1,3,1,"<span class=""token"" data-toggle=""tooltip"" titl...",На какой предпосылке основаны ответы Константи...
3,3,1,4,1,"<span class=""token"" data-toggle=""tooltip"" titl...","Константин Сонин считает, для того чтобы полно..."
4,4,1,5,1,"«<span class=""token"" data-toggle=""tooltip"" ti...","«Средний студент », привыкший быстро справлят..."

In [5]:
tags.head()

   Unnamed: 0  annotator_sentence.id               tag
0           0                   1342  discourse, tauto
1           1                   1345               gov
2           2                   1347              lack
3           3                   1347         lex, word
4           4                   1347               ref

In [6]:
tags = pd.DataFrame(tags.groupby('annotator_sentence.id')['tag'].apply(set))
tags.head()

                                               tag
annotator_sentence.id
1                                            {lex}
4                                             {WO}
6                                           {typo}
8                      {lex, word, styl, official}
12                       {lex, meton, lex, phrase}

In [7]:

def read_data(data, tags):
    tautos_df = pd.merge(data,tags, how='outer',on='annotator_sentence.id')
    tautos_df = tautos_df.loc[tautos_df['annotated'] == 1]
    tautos_df.index=range(51365)
    return tautos_df
tautos_df_new=read_data(data, tags)

In [8]:
tautos_df_new.head()

,Unnamed: 0,annotated,annotator_sentence.id,id,tagged,text,tag
0,0,1,1,1,"<span class=""token"" data-toggle=""tooltip"" titl...",задание 5: В ответах на вопросы использовались...,{lex}
1,1,1,2,1,"«<span class=""token"" data-toggle=""tooltip"" ti...",«Профессора и студент »,NaN
2,2,1,3,1,"<span class=""token"" data-toggle=""tooltip"" titl...",На какой предпосылке основаны ответы Константи...,NaN
3,3,1,4,1,"<span class=""token"" data-toggle=""tooltip"" titl...","Константин Сонин считает, для того чтобы полно...",{WO}
4,4,1,5,1,"«<span class=""token"" data-toggle=""tooltip"" ti...","«Средний студент », привыкший быстро справлят...",NaN

In [9]:
tautos = []
for v in tautos_df_new['tag']:
    if isinstance(v, set) and ('tauto' in v):
        tautos.append(1.0)
    else:
        tautos.append(0.0)
tautos_new=pd.Series(tautos)

In [10]:
tautos_df_new.loc[:,'tautos']=tautos_new
tautos_df_new.head()

,Unnamed: 0,annotated,annotator_sentence.id,id,tagged,text,tag,tautos
0,0,1,1,1,"<span class=""token"" data-toggle=""tooltip"" titl...",задание 5: В ответах на вопросы использовались...,{lex},0.0
1,1,1,2,1,"«<span class=""token"" data-toggle=""tooltip"" ti...",«Профессора и студент »,NaN,0.0
2,2,1,3,1,"<span class=""token"" data-toggle=""tooltip"" titl...",На какой предпосылке основаны ответы Константи...,NaN,0.0
3,3,1,4,1,"<span class=""token"" data-toggle=""tooltip"" titl...","Константин Сонин считает, для того чтобы полно...",{WO},0.0
4,4,1,5,1,"«<span class=""token"" data-toggle=""tooltip"" ti...","«Средний студент », привыкший быстро справлят...",NaN,0.0

In [11]:
tautos_df_new.to_csv('tautos_df.csv')